### ISSUE TITLE
Not all text exported

### ISSUE THREAD

**Issue by imKota** [crskycode/Malie_Script_Tool#1]
Hello, @crskycode
I found bug.

Can you fix it ?
[exec.zip](https://github.com/crskycode/Malie_Script_Tool/files/7482507/exec.zip)

**Comment by crskycode** [comment]
No best way to fix it. Disasm the script, the text instruction pattern is different between games, try to find a instruction pattern from your script.

**Comment by imKota** [comment]
> No best way to fix it. Disasm the script, the text instruction pattern is different between games, try to find a instruction pattern from your script.

it's not bug, lol. 
Because in exe embed EXEC file :D
